### ISSUE TITLE
UI is not redirecting to Keycloak custom domain name

### ISSUE THREAD

**Issue by mboglesby** [opea-project/Enterprise-RAG#74]
I have the following custom domain name specified for Keycloak in my config.yaml:

```
keycloak:
  enabled: true
  namespace: auth
  domainName: auth.aipod-mini-erag.rtp.openenglab.netapp.com
```

Despite this, the UI is redirecting to auth.erag.com instead of auth.aipod-mini-erag.rtp.openenglab.netapp.com. See screenshot below:

![Image](https://github.com/user-attachments/assets/8ebb46d7-7b84-4b2d-b918-87c0c622fee6)
